blog/urls.py
from django.urls import path
from blog.views import PostListView, CreatePostView, PostDetailView

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('create', CreatePostView.as_view(), name='create_post'),
    path('detail/<int:pk>', PostDetailView.as_view(), name='post_detail')
]

kodland_blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=256)
    content = RichTextField(config_name='default')
    image = models.ImageField(upload_to='uploads')
    published_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ('-published_date',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Введите название статьи', 'class': 'post-create__add-title'}),
        }

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView
from blog.models import Post
from blog.forms import PostForm


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    model = Post
    paginate_by = 10


class CreatePostView(CreateView):
    template_name = 'blog/create_post.html'
    form_class = PostForm


class PostDetailView(DetailView):
    template_name = 'blog/post_detail.html'
    model = Post

blog/templates/blog/create_post.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="post-create container">
  <div class="post-create__title">Добавить статью</div>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="post-create__form">
      {{form.title}} {% for error in form.title.errors %}
      <p style="color: red;">{{ error }}</p>

      {% endfor %}
      <input
        type="submit"
        class="button post-create__published"
        value="Опубликовать"
      />
    </div>
    <div class="post-create__form">
      {{form.content}} {% for error in form.content.errors %}
      <p style="color: red;">{{ error }}</p>

      {% endfor %}
      <div class="post-create__image">
        <div class="upload-image__text">
          Загрузить изображение
        </div>
        {{form.image}} {% for error in form.image.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
      </div>
    </div>
  </form>
</div>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor-init.js' %}"
></script>
<script
  type="text/javascript"
  src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"
></script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="post-detail container-small">
  <div class="post-detail__title">
    {{object.title}}
  </div>
  <div class="post-detail__image">
    <img src="{{object.image.url}}" style="width: 100%;" />
  </div>
  <div class="post-detail__content">
    {{object.content|safe}}
  </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %} {% block content %} {% if object_list %}
<div class="post-new">
  <div class="post-new-wrapper container">
    <div class="post-new__text">
      <div class="post-new__new">NEW</div>
      <div class="post-new__title">
        {{object_list.0.title}}
      </div>
      <div class="post-new__content">{{object_list.0.content|safe}}</div>
      <a href="{{object_list.0.get_absolute_url}}">
        <div class="button post-new__button">
          Читать
        </div>
      </a>
    </div>
    <div class="post-new__image">
      <img src="{{object_list.0.image.url}}" style="width: 100%;" />
    </div>
  </div>
</div>
{% else %}
<div class="container post-new__title">Нет постов..</div>
{% endif %} {% if object_list|length > 1 %}
<div class="another-posts container">
  <div class="another-posts__text">
    Другие статьи
  </div>
  <div class="another-posts__grid">
    {% for post in object_list|slice:"1:" %}
    <a href="{{post.get_absolute_url}}">
      <div class="post-card">
        <div class="post-card__date">
          {{post.published_date |date:"d M Y h:i" }}
        </div>
        <div class="post-card__image">
          <img src="{{post.image.url}}" style="width: 100%;" />
        </div>
        <div class="post-card__title">
          {{post.title}}
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endif %} {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "style.css" %}">
    <title>Kodland Blog</title>
  </head>
  <body>
    <div class="header">
      <div class="header__wrapper container">
        <a href="/" class="header__logo">
          <img src="{% static 'images/Logo_Kodland.png' %}" />
          <span class="header__text">Блог</span>
        </a>
        <a href="{% url 'blog:create_post' %}">
          <div class="header__button button">
            + Добавить статью
          </div>
        </a>
      </div>
    </div>
    {% block content %} {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>